export { default as AlertTriangleIcon } from './AlertTriangleIcon.vue'
export { default as ArrowLeftIcon } from './ArrowLeftIcon.vue'
export { default as ArrowRightIcon } from './ArrowRightIcon.vue'
export { default as BriefcaseIcon } from './BriefcaseIcon.vue'
export { default as CalendarIcon } from './CalendarIcon.vue'
export { default as ChatBubbleIcon } from './ChatBubbleIcon.vue'
export { default as CheckBadgeIcon } from './CheckBadgeIcon.vue'
export { default as CheckIcon } from './CheckIcon.vue'
export { default as ChevronDownIcon } from './ChevronDownIcon.vue'
export { default as ChevronLeftIcon } from './ChevronLeftIcon.vue'
export { default as ChevronRightIcon } from './ChevronRightIcon.vue'
export { default as ClockIcon } from './ClockIcon.vue'
export { default as CloseIcon } from './CloseIcon.vue'
export { default as ColumnsLayoutIcon } from './ColumnsLayoutIcon.vue'
export { default as CornerUpLeftIcon } from './CornerUpLeftIcon.vue'
export { default as CrownIcon } from './CrownIcon.vue'
export { default as DeliverablesScopeIcon } from './DeliverablesScopeIcon.vue'
export { default as DownloadIcon } from './DownloadIcon.vue'
export { default as EyeIcon } from './EyeIcon.vue'
export { default as FileIcon } from './FileIcon.vue'
export { default as GlobeIcon } from './GlobeIcon.vue'
export { default as HandshakeIcon } from './HandshakeIcon.vue'
export { default as ImagePlaceholderIcon } from './ImagePlaceholderIcon.vue'
export { default as InfoCircleFilledIcon } from './InfoCircleFilledIcon.vue'
export { default as LinkIcon } from './LinkIcon.vue'
export { default as LoaderIcon } from './LoaderIcon.vue'
export { default as MaximizeIcon } from './MaximizeIcon.vue'
export { default as MegaphoneIcon } from './MegaphoneIcon.vue'
export { default as MoonIcon } from './MoonIcon.vue'
export { default as PackageIcon } from './PackageIcon.vue'
export { default as PaletteIcon } from './PaletteIcon.vue'
export { default as PencilIcon } from './PencilIcon.vue'
export { default as PlusIcon } from './PlusIcon.vue'
export { default as RefreshIcon } from './RefreshIcon.vue'
export { default as RevisionReturnIcon } from './RevisionReturnIcon.vue'
export { default as RocketIcon } from './RocketIcon.vue'
export { default as SendIcon } from './SendIcon.vue'
export { default as ShareIcon } from './ShareIcon.vue'
export { default as SmartphoneIcon } from './SmartphoneIcon.vue'
export { default as SparklesFilledIcon } from './SparklesFilledIcon.vue'
export { default as SparklesIcon } from './SparklesIcon.vue'
export { default as StarIcon } from './StarIcon.vue'
export { default as SunIcon } from './SunIcon.vue'
export { default as TagIcon } from './TagIcon.vue'
export { default as TargetIcon } from './TargetIcon.vue'
export { default as TrendingUpIcon } from './TrendingUpIcon.vue'
export { default as TrophyIcon } from './TrophyIcon.vue'
export { default as ZapIcon } from './ZapIcon.vue'
export type { FileIconProps, IconProps, StrokeIconProps } from './types'

export type IconName =
  | 'alert-triangle'
  | 'arrow-left'
  | 'arrow-right'
  | 'briefcase'
  | 'calendar'
  | 'chat-bubble'
  | 'check'
  | 'check-badge'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'clock'
  | 'close'
  | 'columns-layout'
  | 'corner-up-left'
  | 'crown'
  | 'deliverables-scope'
  | 'download'
  | 'eye'
  | 'file'
  | 'globe'
  | 'handshake'
  | 'image-placeholder'
  | 'info-circle-filled'
  | 'link'
  | 'loader'
  | 'maximize'
  | 'megaphone'
  | 'moon'
  | 'package'
  | 'palette'
  | 'pencil'
  | 'plus'
  | 'refresh'
  | 'revision-return'
  | 'rocket'
  | 'send'
  | 'share'
  | 'smartphone'
  | 'sparkles'
  | 'sparkles-filled'
  | 'star'
  | 'sun'
  | 'tag'
  | 'target'
  | 'trending-up'
  | 'trophy'
  | 'zap'
